-----------------------------------------------
-- Samples with Mouse/Gamepad/Keyboard support
-----------------------------------------------
require("examples.complex_ui.main")
--require("examples.demo_game.main")
--require("examples.demo_ui.main")

-----------------------------------------------
-- other Samples
-----------------------------------------------
--require("examples.virtual_gamepad.main")
--require("examples.flexContainer.main")
--require("examples.nodegraph.main")
--require("examples.editor.main")
--require("examples.gridLayoutTest.main")
--require("examples.basic_ui.main")
--require("examples.guess_game.main")
--require("examples.test.main")
--require("examples.AI_Test.main")
--require("examples.jrpg_battlemenu.main")
--require("examples.luis_suit_test.main")	-- comparision between LUIS and SUIT
